<?php
//
// File generated by Dolibarr installer 8.0.5 on 22 Juil. 2019
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://wdc.dolimed';
$dolibarr_main_document_root='/var/www/html/dolimed/htdocs';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/var/www/html/dolimed/htdocs/custom';
$dolibarr_main_data_root='/var/www/html/dolimed/documents';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='5432';
$dolibarr_main_db_name='dolimed';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='dolimed';
$dolibarr_main_db_pass='dolimed';
$dolibarr_main_db_type='pgsql';
$dolibarr_main_db_character_set='UTF8';
$dolibarr_main_db_collation='C.UTF-8';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_cookie_cryptkey='d58d0dde99237a5561681c692533af11';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
